Repository WildCodeSchool-2024-09/JS-RemoteFR-Vendangeurs-P3-WildCom, pull requests merged in 2025-01, with the labels that each got.

#11 S1 u8 refactoring
  client/src/main.tsx
  client/src/pages/Acceuil.tsx
  client/src/pages/Home.tsx
Labels: REVIEWD

#14 [FEAT] S1-U6-add profile page and route
  client/src/App.tsx
  client/src/assets/images/myprofile.png
  client/src/assets/images/userprofile.png
  client/src/components/SideNavigation.tsx
  client/src/main.tsx
  client/src/pages/Profil.tsx
Labels: CHANGE_REQUESTED, CORRECTIONS_DONE, REVIEWD

#16 S1 u2 contact
  client/src/components/Footer.tsx
Labels: CHANGE_REQUESTED, CORRECTIONS_DONE

#17 [FEAT] : add cards on home page
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/demo/fog.jpg
  client/src/assets/images/demo/landscape.jpg
  client/src/assets/images/demo/man.jpg
  client/src/assets/images/demo/sea.jpg
  client/src/assets/images/demo/woman1.jpg
  client/src/assets/images/demo/woman2.jpg
  client/src/assets/images/settings.svg
  client/src/components/Navigation.tsx
  client/src/pages/Events.tsx
  client/src/pages/Home.tsx
Labels: CHANGE_REQUESTED, CORRECTIONS_DONE, REVIEWD

#32 [FEAT] : Add event back with routes
  client/src/pages/Events.tsx
  server/database/schema.sql
  server/src/modules/event/eventActions.ts
  server/src/modules/event/eventRepository.ts
  server/src/router.ts
Labels: REVIEWD

#34 S2 u27 routing profile
  client/src/pages/Profil.tsx
  server/database/schema.sql
  server/src/modules/profile/profilRepository.ts
  server/src/modules/profile/profileActions.ts
  server/src/router.ts
Labels: CONFLICTS_RESOLVED

#35 S2 u28 api get all comments
  server/database/schema.sql
  server/src/modules/post/postComment/postCommentsActions.ts
  server/src/modules/post/postComment/postCommentsRepository.ts
  server/src/router.ts
Labels: CONFLICTS_RESOLVED, REVIEWD

#36 S2 u20 create event page
  client/src/assets/images/place.png
  client/src/pages/Events.tsx
  server/database/schema.sql
  server/src/modules/event/eventActions.ts
  server/src/modules/event/eventRepository.ts
Labels: REVIEWD

#37 [REFACTOR] replace profil by user in routing profile
  client/package.json
  client/src/assets/images/calendar.png
  client/src/components/Navigation.tsx
  client/src/pages/Profil.tsx
  package-lock.json
  server/database/schema.sql
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: CHANGE_REQUESTED, CORRECTIONS_DONE

#42 [REFACTOR] replace icons with react icons
  client/src/App.tsx
  client/src/components/Navigation.tsx
  client/src/components/SideNavigation.tsx
  client/src/pages/Events.tsx
Labels: REVIEWD

#44 [FEAT] : add event comment route
  server/database/schema.sql
  server/src/modules/event/eventComment/eventCommentActions.ts
  server/src/modules/event/eventComment/eventCommentRepository.ts
  server/src/router.ts
Labels: REVIEWD

#60 [FEAT] : add new post bdd
  server/src/app.ts
  server/src/modules/event/eventActions.ts
  server/src/modules/post/postActions.ts
  server/src/modules/post/postRepository.ts
  server/src/router.ts
Labels: REVIEWD

#61 [feat] creating a comment route in a post
  server/src/modules/post/postComment/postCommentsActions.ts
  server/src/modules/post/postComment/postCommentsRepository.ts
  server/src/router.ts
Labels: REVIEWD

#67 S3 u54 comment posts
  client/src/components/CardPost.tsx
  client/src/components/PostComment/CommentInput.tsx
Labels: REVIEWD

#105 [FEAT] menu creation in mobile version
  client/src/components/Layout/Header.tsx
  client/src/components/Navigation/MobileNav.tsx
Labels: REVIEWD

#107 S5 u8 refacto
  client/src/components/ModalButton.tsx
  client/src/components/Navigation/RightNav.tsx
  server/src/modules/post/postActions.ts
Labels: REVIEWD

#114 [FEAT]: add modification system on comment post
  client/src/components/CommentPost.tsx
Labels: REVIEWD

#116 S4 u70 modify post back
  client/src/components/CardEvent.tsx
  client/src/components/CardPost.tsx
  client/src/components/EventModal.tsx
  client/src/components/PostModal.tsx
  client/src/types/type.ts
  server/database/schema.sql
  server/src/modules/category/categoryActions.ts
  server/src/modules/category/categoryRepository.ts
  server/src/modules/event/eventRepository.ts
  server/src/modules/post/postActions.ts
  server/src/modules/post/postRepository.ts
  server/src/modules/user/userPost/userPostRepository.ts
  server/src/router.ts
Labels: REVIEWD
